services:
  posts-service:
    build: 
      context: ./posts
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  comments-service:
    build:
      context: ./comments
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
  
  query-service:
    build:
      context: ./query
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
  
  moderation-service:
    build:
      context: ./moderation
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
  
  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"